window.questionBank = {
    "Frontend Basics (HTML & CSS)": [
        { q: "What is the main purpose of CSS?", options: ["Structure", "Interactivity", "Styling/Design", "Database storage"], correct: 2 },
        { q: "Which tool automatically generates core code based on English prompts?", options: ["GitHub", "SQL", "HTML", "Antigravity"], correct: 3 },
        { q: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Multi", "Home Tool", "Hyperlinks and Text"], correct: 0 },
        { q: "Which technology natively ensures websites collapse properly on mobile phone screens?", options: ["JavaScript", "HTML Layouting", "CSS Media Queries", "PostgreSQL"], correct: 2 },
        { q: "Which HTML tag is used for the largest heading?", options: ["<h6>", "<header>", "<head>", "<h1>"], correct: 3 },
        { q: "What does CSS stand for?", options: ["Cascading Style Sheets", "Creative Style System", "Computer Style Scripts", "Code Styling Sheets"], correct: 0 },
        { q: "Which of these is correct for a CSS comment?", options: ["// comment", "<!-- comment -->", "/* comment */", "' comment"], correct: 2 },
        { q: "Which property is used to change the background color?", options: ["color", "background-color", "bgcolor", "bg-style"], correct: 1 },
        { q: "Which property changes text color in CSS?", options: ["text-color", "font-color", "color", "textColor"], correct: 2 },
        { q: "What is the correct HTML element for inserting a line break?", options: ["<break>", "<lb>", "<br>", "<newline>"], correct: 2 },
        { q: "Which character indicates an HTML end tag?", options: ["^", "/", "*", "<"], correct: 1 },
        { q: "How do you select an element with id 'demo' in CSS?", options: ["#demo", ".demo", "demo", "*demo"], correct: 0 },
        { q: "How do you select elements with class name 'test'?", options: ["#test", ".test", "test", "*test"], correct: 1 },
        { q: "Which CSS property controls the text size?", options: ["font-style", "text-size", "font-size", "text-style"], correct: 2 },
        { q: "Which of these is an example of an inline HTML element?", options: ["<div>", "<p>", "<span>", "<h1>"], correct: 2 },
        { q: "Which HTML attribute specifies an alternate text for an image?", options: ["alt", "title", "src", "href"], correct: 0 },
        { q: "In HTML, numbered lists are created with what tag?", options: ["<ul>", "<list>", "<ol>", "<dl>"], correct: 2 },
        { q: "Which HTML tag makes text bold?", options: ["<bold>", "<strong>", "<i>", "<mark>"], correct: 1 },
        { q: "What does the 'href' attribute do in an anchor tag?", options: ["Highlights the link", "Hides the link", "Points to the destination URL", "Runs a script"], correct: 2 },
        { q: "Which layout model is best for 1-dimensional row/column alignment?", options: ["Grid", "Flexbox", "Float", "Table"], correct: 1 },
        { q: "Which CSS unit is relative to the viewport width?", options: ["px", "em", "vw", "rem"], correct: 2 },
        { q: "Which HTML5 semantic tag defines navigation links?", options: ["<nav>", "<header>", "<section>", "<footer>"], correct: 0 },
        { q: "Which CSS property adds space inside an element's border?", options: ["padding", "margin", "spacing", "gap"], correct: 0 },
        { q: "What does the z-index property do in CSS?", options: ["Zooms the element", "Sets the opacity", "Controls the stacking order of overlapping elements", "Creates a 3D transformation"], correct: 2 },
        { q: "Which command centers text in CSS?", options: ["align-text: center;", "text-align: center;", "center-text: true;", "margin: auto;"], correct: 1 }
    ],
    "JavaScript Mastery": [
        { q: "Which language solely adds dynamic logic and interactivity to a webpage?", options: ["CSS", "JavaScript", "HTML", "SQL"], correct: 1 },
        { q: "What native function lets JavaScript request data natively without reloading?", options: ["reload()", "fetch()", "get()", "ping()"], correct: 1 },
        { q: "Where should authentic VIP JWT tokens be securely saved on the frontend?", options: ["In CSS files", "In the console", "Local Storage / Cookies", "HTML limit"], correct: 2 },
        { q: "Why use React instead of vanilla JS directly?", options: ["Reusable component architecture", "Prevents all hacking instantly", "Replaces databases", "Removes CSS requirements"], correct: 0 },
        { q: "Inside which HTML element do we put JavaScript?", options: ["<js>", "<scripting>", "<javascript>", "<script>"], correct: 3 },
        { q: "How do you write 'Hello World' in an alert box?", options: ["msgBox('Hello World');", "alertBox('Hello World');", "alert('Hello World');", "prompt('Hello World');"], correct: 2 },
        { q: "How do you create a function in JavaScript?", options: ["function myFunction()", "function:myFunction()", "function = myFunction()", "create myFunction()"], correct: 0 },
        { q: "How do you call a function named 'myFunction'?", options: ["call function myFunction()", "call myFunction()", "myFunction()", "execute myFunction()"], correct: 2 },
        { q: "How to write an IF statement in JavaScript?", options: ["if i = 5 then", "if i == 5 then", "if (i == 5)", "if i = 5"], correct: 2 },
        { q: "How does a WHILE loop start?", options: ["while i = 1 to 10", "while (i <= 10; i++)", "while (i <= 10)", "while (i <= 10) do"], correct: 2 },
        { q: "How can you add a comment in JavaScript?", options: ["// This is a comment", "<!-- This is a comment -->", "' This is a comment", "/* This is a comment */"], correct: 0 },
        { q: "Which built-in JS method returns the length of a string?", options: ["size()", "length()", "length", "index()"], correct: 2 },
        { q: "How do you declare a JavaScript variable?", options: ["variable carName;", "var carName;", "v carName;", "declare carName;"], correct: 1 },
        { q: "Which operator is used to assign a value to a variable?", options: ["*", "-", "=", "x"], correct: 2 },
        { q: "What will typeof [1, 2, 3] return?", options: ["array", "string", "object", "number"], correct: 2 },
        { q: "Is JavaScript case-sensitive?", options: ["Yes", "No", "Only for variables", "Only for functions"], correct: 0 },
        { q: "What does 'DOM' stand for?", options: ["Data Object Model", "Document Object Model", "Dynamic Object Mechanism", "Document Oriented Makeup"], correct: 1 },
        { q: "Which method is used to get an element by ID?", options: ["getElement(id)", "querySelector(id)", "getElementById(id)", "find(id)"], correct: 2 },
        { q: "Which keyword is used to define immutable variables?", options: ["let", "var", "const", "static"], correct: 2 },
        { q: "What does the '===' operator do?", options: ["Assigns values", "Compares values only", "Compares values and types strictly", "Performs math"], correct: 2 },
        { q: "What is an arrow function?", options: ["A function pointing to HTML", "A shorter syntax for writing function expressions: () => {}", "A loop structure", "A math object"], correct: 1 },
        { q: "What does JSON.stringify() do?", options: ["Parses a string into JSON", "Converts a JavaScript object into a JSON string", "Executes JSON format", "Logs data"], correct: 1 },
        { q: "Which method immediately adds a new item to the end of an array?", options: ["pop()", "push()", "shift()", "add()"], correct: 1 },
        { q: "What is the purpose of 'setTimeout'?", options: ["To delete an element", "To pause the server", "To execute a function after a delay", "To loop infinitely"], correct: 2 },
        { q: "What object is automatically passed into an event listener function?", options: ["The Event object", "The DOM tree", "The user's IP", "The JSON file"], correct: 0 }
    ],
    "Backend & Databases": [
        { q: "Which of these is inherently a structured Relational SQL database?", options: ["MongoDB", "PostgreSQL", "Firebase Document", "Redis Cache"], correct: 1 },
        { q: "What natively acts precisely as the API 'Operator' between the browser and database?", options: ["CSS Properties", "The Backend Web Server App", "The Browser Console", "The Local Storage Memory"], correct: 1 },
        { q: "What represents the exact 'Menu' URLs that frontends use to trigger logic?", options: ["File extensions", "The HTTP API Paths (e.g. /api/login)", "A DNS Registry", "HTML classes"], correct: 1 },
        { q: "For highly strict Banking apps demanding rigid rows, what DB paradigm is best?", options: ["A NoSQL Document DB", "A Frontend Text File", "A SQL Relational DB", "Cloudinary Hosting"], correct: 2 },
        { q: "What is Node.js?", options: ["A frontend framework", "A JavaScript runtime built on Chrome's V8 engine allowing JS on servers", "A SQL Database component", "A CSS preprocessor"], correct: 1 },
        { q: "What is npm?", options: ["Network Protocol Manager", "Node Package Manager", "New Project Module", "No Problem Mode"], correct: 1 },
        { q: "Which HTTP method is utilized explicitly to retrieve data?", options: ["POST", "PUT", "DELETE", "GET"], correct: 3 },
        { q: "Which HTTP method is meant for permanently creating new data on the server?", options: ["POST", "GET", "PATCH", "DELETE"], correct: 0 },
        { q: "What is the difference between SQL and NoSQL?", options: ["SQL is for frontend, NoSQL is backend", "SQL uses structured tables; NoSQL uses flexible documents", "SQL is faster for small files", "There is no difference"], correct: 1 },
        { q: "What does CRUD stand for?", options: ["Create, Read, Update, Delete", "Copy, Run, Upload, Download", "Create, Run, Update, Drop", "Code, Read, Undo, Deploy"], correct: 0 },
        { q: "What is an ORM?", options: ["Object-Relational Mapper (converts DB rows into JS objects)", "Origin Resource Mechanism", "Operational Routing Method", "Online Request Manager"], correct: 0 },
        { q: "Why use Environment Variables (.env)?", options: ["To style the console", "To hide secrets like API keys outside the public source code", "To speed up the network", "To store HTML templates"], correct: 1 },
        { q: "In databases, what is a Primary Key?", options: ["The password to enter", "A unique identifier strictly enforcing uniqueness for each row", "The most important table column", "The server's IP"], correct: 1 },
        { q: "What is Express.js?", options: ["A database", "A fast, unopinionated web framework for Node.js", "A frontend library", "An operating system"], correct: 1 },
        { q: "What type of data format is primarily used inside modern REST APIs?", options: ["XML", "CSV", "YAML", "JSON"], correct: 3 },
        { q: "What does 'localhost:3000' represent?", options: ["The public internet", "A local development server running on port 3000", "A database cluster", "An error code"], correct: 1 },
        { q: "In standard MongoDB, what groups documents together?", options: ["Tables", "Collections", "Arrays", "Databases"], correct: 1 },
        { q: "What is a major advantage of NoSQL architectures?", options: ["Perfectly strict data columns", "Total lack of IDs", "Easier tracking of relations", "High scalability and flexible schema-less design"], correct: 3 },
        { q: "What does the 'req' object represent in typical Express routes?", options: ["The response to send back", "The incoming HTTP Request from the client", "Database query results", "The routing engine"], correct: 1 },
        { q: "What creates a standard 404 Error?", options: ["Bad Password", "The requested URL route was inherently not found on the server", "A syntax bug in code", "Database disconnected"], correct: 1 },
        { q: "Which tool is commonly used to manually test API endpoints without building a frontend?", options: ["Postman / Insomnia", "Photoshop", "Git", "Google Analytics"], correct: 0 },
        { q: "How is data typically passed secretly via a GET request?", options: ["In the URL Query String parameters", "In the Body payload", "In the CSS", "It cannot be passed"], correct: 0 },
        { q: "What does SQL stand for?", options: ["Strong Question Logic", "Structured Query Language", "Standard Query Link", "Secret Query Loop"], correct: 1 },
        { q: "What limits excessive requests from the same user to prevent spam?", options: ["Rate Limiting middleware", "A SQL Drop rule", "Local storage", "A fast router"], correct: 0 },
        { q: "What represents the middleware chain in a server app?", options: ["The index file", "Functions that execute sequentially modifying requests before the final route logic", "The HTML files", "Database drivers"], correct: 1 }
    ],
    "Architecture & Security": [
        { q: "What does the DNS system natively do?", options: ["Compiles React code", "Styles buttons", "Translates generic URLs to exact mathematical IP addresses", "Protects servers"], correct: 2 },
        { q: "Which HTTP connection encrypts data so public Wi-Fi interceptors see gibberish?", options: ["HTTP", "HTTPS", "FTP", "REST"], correct: 1 },
        { q: "Which concept represents Authorization (AuthZ) instead of Authentication (AuthN)?", options: ["Scanning an employee fingerprint ID", "Ensuring user password hashes match", "Verifying the logged-in employee explicitly lacks clearance to open the vault", "Encrypting with certificates"], correct: 2 },
        { q: "What mitigates SQL Injection attacks effectively?", options: ["Paramterized Queries / Prepared Statements", "Changing CSS variables", "Writing longer passwords", "Avoiding HTML"], correct: 0 },
        { q: "What is Cross-Site Scripting (XSS)?", options: ["Sending cross-origin CSS", "Injecting malicious executable scripts into the web pages viewed by other users", "Stealing databases", "Merging Git Branches"], correct: 1 },
        { q: "What exactly dictates CORS policies?", options: ["The frontend JavaScript", "The Browser enforcing server-defined boundaries on cross-origin fetching", "The Database", "The VPN router"], correct: 1 },
        { q: "What is securely used to hash passwords before database storage?", options: ["Base64 Encoders", "bcrypt / Argon2 hashing algorithms", "JSON generators", "MD5 algorithms"], correct: 1 },
        { q: "Why should you never store passwords in plain text?", options: ["It uses too much database limit", "If the strict database leaks, all users are instantly compromised", "Because computers cannot read Strings", "It crashes the UI"], correct: 1 },
        { q: "What is a JWT (JSON Web Token)?", options: ["A CSS framework", "A secure, compact URL-safe token representing claims between two parties", "A Database URL", "A Git Branching tool"], correct: 1 },
        { q: "Where does the JWT signature check technically happen to verify integrity?", options: ["On the Client browser", "Deep inside the Backend Server", "In the DNS lookup", "Inside the Git repository"], correct: 1 },
        { q: "What is the aggressive primary role of a CI/CD pipeline on a software team?", options: ["Write CSS autonomously", "Automatically run strict tests and deploy passing code to live remote servers", "Defend against DDoS natively", "Translates IPs"], correct: 1 },
        { q: "What signifies a DDoS attack?", options: ["Injecting a script", "Flooding a server relentlessly with enormous traffic to brutally overwhelm it", "Stealing a user JWT", "Hacking the Admin panel directly"], correct: 1 },
        { q: "What mitigates DDoS attacks?", options: ["Firewalls and Load Balancers (like Cloudflare)", "CSS rules", "Git ignores", "Strong user passwords"], correct: 0 },
        { q: "What defines a man-in-the-middle (MITM) attack?", options: ["A developer making Git conflicts", "An attacker strategically intercepting data traffic between two parties", "A bug in the Node.js middleware", "A dropped database column"], correct: 1 },
        { q: "To effectively store sensitive configuration variables securely on hosting like Vercel, you use:", options: ["Public JSON files", "Index HTML tags", "Environment Variables (.env)", "GitHub README files"], correct: 2 },
        { q: "Which Status Code indicates a successful generalized HTTP Response?", options: ["404 Not Found", "200 OK", "500 Internal Error", "403 Forbidden"], correct: 1 },
        { q: "Which Status Code dictates the user lacks authorization or clearance?", options: ["200 OK", "500 Error", "403 / 401 Forbidden", "302 Redirect"], correct: 2 },
        { q: "What is a VPN physically?", options: ["A SQL cache", "A Virtual Private Network extending isolated secure tunnels across the internet", "A Javascript library", "A local frontend state"], correct: 1 },
        { q: "What constitutes the 'frontend' in MVC design patterns?", options: ["Model", "View", "Controller", "All of the Above"], correct: 1 },
        { q: "What happens if a backend doesn't scrub (sanitize) HTML input?", options: ["XSS vulnerabilities exist where users can inject raw executing scripts", "The database crashes", "CSS breaks", "Files delete automatically"], correct: 0 },
        { q: "What does HTTPS rely on fundamentally for encryption?", options: ["TLS / SSL Certificates", "Strong passwords", "Node.js code", "Vercel hosting"], correct: 0 },
        { q: "What determines exactly how fast a CDN (Content Delivery Network) loads sites?", options: ["How complex the backend is", "Bringing static cached assets geographically closer to the user", "The size of the hard drive", "The DNS registry"], correct: 1 },
        { q: "What acts as the final manager in a factory confirming testing passing before dropping code to live production automatically?", options: ["The Developer", "The Database ORM", "The CI/CD workflow Pipeline", "A Git Commit message"], correct: 2 },
        { q: "Which automated tooling system is famous for mocking heavy browser clicks efficiently like a human testing?", options: ["Cypress", "Node", "PostgreSQL", "Tailwind"], correct: 0 },
        { q: "What is a 'Zero-Day' Vulnerability?", options: ["A bug occurring on launch day", "A security flaw severely unknown to software developers making patches completely unavailable natively", "A database deleted completely", "Having no code to commit"], correct: 1 }
    ],
    "Git & GitHub Workflows": [
        { q: "Which system acts exactly like manual 'Checkpoints' logically in a video game?", options: ["Git", "React", "Node Server", "MongoDB"], correct: 0 },
        { q: "What does 'git add .' accomplish perfectly?", options: ["Takes final snapshot", "Pushes to GitHub", "Gathers exclusively modified files safely into a staging area readiness", "Creates a repo"], correct: 2 },
        { q: "Which Git command securely clones an isolated, parallel universe to safely experiment?", options: ["git commit", "git merge", "git push", "git branch"], correct: 3 },
        { q: "Where does GitHub permanently host your pushed codebase?", options: ["Locally inside .git", "Securely inside remote Cloud Servers", "Isolated on Desktop", "In Local memory"], correct: 1 },
        { q: "What file purely protects passwords and system specs from being tracked to GitHub?", options: ["README.md", "package.json", "index.html", ".gitignore"], correct: 3 },
        { q: "To cleanly fuse an experimental feature branch heavily back into the 'main' timeline, what command triggers?", options: ["git fuse", "git merge", "git checkout origin", "git init --bare"], correct: 1 },
        { q: "What specifically does 'git init' do?", options: ["Translates code", "Initializes a blank local Git tracking repository exactly in that folder", "Deletes Git configs", "Pushes to GitHub"], correct: 1 },
        { q: "What happens when you run 'git clone'?", options: ["Copies a local folder", "Connects to a server", "Downloads a complete, pre-configured isolated copy of a huge remote project", "It creates a branch"], correct: 2 },
        { q: "Which command explicitly sends local snapshots strictly up to the cloud repository?", options: ["git push", "git pull", "git send", "git upload"], correct: 0 },
        { q: "Which command routinely synchronizes a colleague's remote cloud changes onto your hard drive?", options: ["git push", "git receive", "git pull", "git download"], correct: 2 },
        { q: "What does 'git status' reveal intuitively?", options: ["The entire code structure", "The current active branch and distinctly which files are staged/unstaged natively", "The commit history log", "Your GitHub password"], correct: 1 },
        { q: "What commands are combined heavily when running a comprehensive 'git pull' internally?", options: ["add and commit", "push and verify", "fetch and merge", "checkout and switch"], correct: 2 },
        { q: "How do you view the previous sequence of all tracked snapshots?", options: ["git list", "git show", "git log", "git history"], correct: 2 },
        { q: "What acts precisely as the front-page explanation document indicating how an Open Source repo works intuitively?", options: ["index.html", "README.md written precisely in Markdown", "server.js", ".gitignore"], correct: 1 },
        { q: "What does 'git checkout <branch_name>' immediately do?", options: ["Pushes code dynamically", "Merges logic forcefully", "Physically switches your active working directory uniquely into that branch's timeline", "Deletes branches logically"], correct: 2 },
        { q: "What creates a Git Merge Conflict natively?", options: ["Changing a password", "When two people uniquely edit the exact same code line differently asynchronously", "When the server goes down completely", "When you skip a commit heavily"], correct: 1 },
        { q: "What happens forcefully if you delete the hidden .git directory heavily?", options: ["GitHub crashes natively", "Your code remains fully but you permanently wipe your entire history and logical tracking ability", "Nothing affects heavily", "The branch drops totally"], correct: 1 },
        { q: "What does 'Forking' mean openly on GitHub?", options: ["Splitting code natively", "Creating a duplicated repository inside your independent account permanently so you own it", "Deleting issues explicitly", "Running tests independently"], correct: 1 },
        { q: "What exactly is a Pull Request (PR)?", options: ["A download heavily", "A formalized message alerting senior developers requesting permission to natively merge your separated code in", "An error code natively", "A CSS styling issue"], correct: 1 },
        { q: "What does explicitly 'git commit -m \"message\"' enforce primarily?", options: ["Tags a commit securely with an explanatory descriptive string logically", "Mutes warnings independently", "Sends code over network primarily", "Ignores files safely"], correct: 0 },
        { q: "What represents the absolute HEAD fundamentally in Git logic?", options: ["The GitHub server centrally", "A pointer referencing strictly the latest checkout commit exclusively in the active timeline", "The admin password securely", "A main structural layout"], correct: 1 },
        { q: "Why securely set global email logic heavily in Git configs fundamentally?", options: ["To log into Github heavily", "To explicitly tie an identifiable authorship to every logical snapshot created locally", "To get Git newsletters dynamically", "To avoid server timeouts independently"], correct: 1 },
        { q: "What heavily distinguishes 'git pull' explicitly from 'git fetch' fundamentally?", options: ["Pull forcefully merges changes independently into working directories instead of just downloading logs uniquely", "Fetch pushes codes globally inside branches securely", "Pull requires passwords explicitly", "Fetch ignores configs centrally"], correct: 0 },
        { q: "What happens centrally when explicitly running 'git push origin main' globally?", options: ["The repository updates entirely locally securely", "You push local logically snapshot logs upward distinctly to the cloud target named 'origin' extensively", "It resets CSS variables intelligently", "It forces merges extensively"], correct: 1 },
        { q: "To extensively un-stage a wrongly added file intelligently without deleting code, you use:", options: ["git reset strictly", "git remove dynamically", "git push logically", "git fetch intelligently"], correct: 0 }
    ]
};
